Repository elastic/elasticsearch-py, pull requests merged in 2020-12, with the labels that each got.

#1458 Start using wipe_cluster() for ensuring consistency
  .ci/certs/ca.crt
  .ci/certs/ca.pem
  .ci/certs/testnode.crt
  .ci/certs/testnode.key
  test_elasticsearch/test_async/test_server/conftest.py
  test_elasticsearch/test_async/test_server/test_helpers.py
  test_elasticsearch/test_async/test_server/test_rest_api_spec.py
  test_elasticsearch/test_server/conftest.py
  test_elasticsearch/test_server/test_rest_api_spec.py
  test_elasticsearch/utils.py
Labels: backport 7.10, backport 7.x

#1460 Support IPv6 braces in Connection.host
  elasticsearch/connection/base.py
  test_elasticsearch/test_connection.py
Labels: backport 7.10, backport 7.x

#1465 [DOCS] Adds Connecting section to Python book
  docs/guide/connecting.asciidoc
  docs/guide/index.asciidoc
Labels: 7.x, backport 7.x, docs

#1473 Add the 'X-Elastic-Client-Meta' header
  elasticsearch/_async/http_aiohttp.py
  elasticsearch/_async/http_aiohttp.pyi
  elasticsearch/connection/base.py
  elasticsearch/connection/base.pyi
  elasticsearch/connection/http_requests.py
  elasticsearch/connection/http_requests.pyi
  elasticsearch/connection/http_urllib3.py
  elasticsearch/connection/http_urllib3.pyi
  elasticsearch/helpers/actions.py
  test_elasticsearch/test_async/test_connection.py
  test_elasticsearch/test_connection.py
  test_elasticsearch/test_helpers.py
Labels: backport 7.10, backport 7.x

#1477 Handle Python pre-releases properly in meta header
  .github/workflows/ci.yml
  elasticsearch/connection/base.py
  test_elasticsearch/test_connection.py
Labels: backport 7.x

#1480 Move client meta logic to Transport
  elasticsearch/_async/helpers.py
  elasticsearch/_async/http_aiohttp.py
  elasticsearch/_async/transport.py
  elasticsearch/connection/base.py
  elasticsearch/connection/http_requests.py
  elasticsearch/connection/http_urllib3.py
  elasticsearch/helpers/actions.py
  elasticsearch/transport.py
  elasticsearch/transport.pyi
  elasticsearch/utils.py
  elasticsearch/utils.pyi
  test_elasticsearch/test_async/test_connection.py
  test_elasticsearch/test_async/test_transport.py
  test_elasticsearch/test_connection.py
  test_elasticsearch/test_helpers.py
  test_elasticsearch/test_transport.py
  test_elasticsearch/test_utils.py
Labels: backport 7.11, backport 7.x

#1479 the variable indices assigned twice
  elasticsearch/_async/client/__init__.py
  elasticsearch/client/__init__.py
Labels: backport 7.10, backport 7.11, backport 7.x

#1487 Move tarball step into .ci/make.sh
  .ci/make.sh
Labels: backport 7.10, backport 7.11, backport 7.x
