Repository elastic/elasticsearch-py, pull requests merged in 2020-10, with the labels that each got.

#1393 [DOCS] Reorganizes Overview and Installation chapters
  docs/guide/index.asciidoc
  docs/guide/installation.asciidoc
  docs/guide/overview.asciidoc
Labels: backport 7.x, docs

#1394 Fix Connection.log_*() body parameter type
  elasticsearch/connection/base.pyi
  elasticsearch/connection/http_requests.py
  test_elasticsearch/test_connection.py
Labels: backport 7.x

#1398 Add .ci/make.sh script for building releases
  .ci/make.sh
  .github/workflows/ci.yml
  .gitignore
  elasticsearch/__init__.py
  setup.py
  utils/build_dists.py
Labels: backport 7.10, backport 7.x

#1401 Remove yarl from [async] extra
  elasticsearch/_async/_extra_imports.py
  elasticsearch/_async/http_aiohttp.py
  noxfile.py
  setup.py
  test_elasticsearch/test_async/test_server/test_clients.py
Labels: backport 7.10, backport 7.9, backport 7.x
