Repository elastic/elasticsearch-py, pull requests merged in 2020-03, with the labels that each got.

#1133 add enrich section to xpack documentation
  docs/xpack.rst
Labels: affects 6.x, affects 7.x

#1143 Restore default metric='_all' to cluster.state()
  elasticsearch/client/cluster.py
  test_elasticsearch/test_client/test_cluster.py
  test_elasticsearch/test_client/test_indices.py
  test_elasticsearch/test_server/__init__.py
  utils/templates/overrides/cluster/state
Labels: affects 7.x

#1135 Add support for X-Opaque-Id
  docs/api.rst
  elasticsearch/client/__init__.py
  elasticsearch/client/cat.py
  elasticsearch/client/ccr.py
  elasticsearch/client/cluster.py
  elasticsearch/client/enrich.py
  elasticsearch/client/graph.py
  elasticsearch/client/ilm.py
  elasticsearch/client/indices.py
  elasticsearch/client/ingest.py
  elasticsearch/client/license.py
  elasticsearch/client/migration.py
  elasticsearch/client/ml.py
  elasticsearch/client/monitoring.py
  elasticsearch/client/nodes.py
  elasticsearch/client/rollup.py
  elasticsearch/client/security.py
  elasticsearch/client/slm.py
  elasticsearch/client/snapshot.py
  elasticsearch/client/sql.py
  elasticsearch/client/ssl.py
  elasticsearch/client/tasks.py
  elasticsearch/client/transform.py
  elasticsearch/client/utils.py
  elasticsearch/client/watcher.py
  elasticsearch/client/xpack.py
  elasticsearch/connection/base.py
  elasticsearch/connection/http_requests.py
  elasticsearch/connection/http_urllib3.py
  elasticsearch/transport.py
  test_elasticsearch/test_cases.py
  test_elasticsearch/test_client/__init__.py
  test_elasticsearch/test_client/test_utils.py
  test_elasticsearch/test_connection.py
  test_elasticsearch/test_server/test_common.py
  test_elasticsearch/test_transport.py
  utils/templates/base
  utils/templates/func_params
  utils/templates/overrides/__init__/clear_scroll
  utils/templates/overrides/__init__/index
  utils/templates/overrides/__init__/scroll
  utils/templates/overrides/cluster/stats
Labels: affects 7.x

#1128 Update Cloud ID default port, parsing of Cloud ID
  docs/index.rst
  elasticsearch/connection/base.py
  elasticsearch/connection/http_requests.py
  elasticsearch/connection/http_urllib3.py
  elasticsearch/transport.py
  test_elasticsearch/test_connection.py
  test_elasticsearch/test_transport.py
Labels: affects 6.x, affects 7.x

#1180 Support serializing numpy and pandas types
  dev-requirements.txt
  elasticsearch/serializer.py
  test_elasticsearch/test_serializer.py
  test_elasticsearch/test_server/test_common.py
Labels: 6.x, 7.x

#1179 Surface deprecation warnings from Elasticsearch
  elasticsearch/__init__.py
  elasticsearch/connection/base.py
  elasticsearch/connection/http_requests.py
  elasticsearch/connection/http_urllib3.py
  elasticsearch/exceptions.py
  elasticsearch/helpers/test.py
  test_elasticsearch/test_connection.py
  test_elasticsearch/test_server/test_common.py
Labels: 6.x, 7.x

#1183 Add certifi as a dependency
  setup.py
  test_elasticsearch/test_server/test_common.py
Labels: 6.x
