Repository elastic/elasticsearch-py, pull requests merged in 2021-08, with the labels that each got.

#1645 Support data stream re-indexing
  elasticsearch/_async/client/nodes.py
  elasticsearch/_async/client/sql.py
  elasticsearch/_async/helpers.py
  elasticsearch/_async/helpers.pyi
  elasticsearch/client/nodes.py
  elasticsearch/client/sql.py
  elasticsearch/helpers/actions.py
  elasticsearch/helpers/actions.pyi
  elasticsearch/helpers/test.py
  test_elasticsearch/test_async/test_server/test_helpers.py
  test_elasticsearch/test_server/test_helpers.py
Labels: backport 7.x

#1657 Publish release notes for 7.14.0
  docs/guide/release-notes.asciidoc
Labels: backport 7.13, backport 7.14, backport 7.x

#1668 Disable Python 3.10 integration tests, fix Python 2.7 test suite
  .ci/test-matrix.yml
  .github/workflows/ci.yml
  dev-requirements.txt
  test_elasticsearch/test_server/test_helpers.py
Labels: backport 7.14, backport 7.x

#1679 Cleanup README and unused files
  .coveragerc
  AUTHORS
  Changelog.rst
  MANIFEST.in
  Makefile
  README.rst
  setup.py
Labels: backport 7.x, backport 7.14

#1683 Add documentation for using the client in FaaS environments
  docs/guide/connecting.asciidoc
Labels: backport 7.x, backport 7.14

#1672 Add explicit parameters for AIOHttpConnection and AsyncTransport
  elasticsearch/_async/http_aiohttp.py
  elasticsearch/_async/http_aiohttp.pyi
  elasticsearch/_async/transport.py
  elasticsearch/_async/transport.pyi
Labels: backport 7.x

#1700 Fixing `rest_api_spec` failures
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.x, backport 7.15

#1701 Fix Pipelines
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.x, backport 7.14, backport 7.15
