Repository elastic/elasticsearch-py, pull requests merged in 2021-04, with the labels that each got.

#1564 [DOCS] Adds Client helpers section to Py book
  docs/guide/helpers.asciidoc
  docs/guide/index.asciidoc
Labels: 7.x, 8.x, docs

#1565 [7.x][DOCS] Adds Client helpers section to Py book
  docs/guide/helpers.asciidoc
  docs/guide/index.asciidoc
Labels: 7.x, backport 7.x, docs

#1571 Add option to set up `client_cert` & `client_key` for aio requests
  elasticsearch/_async/http_aiohttp.py
Labels: backport 7.12, backport 7.x

#1566 spelling of `Interesting`
  docs/guide/examples.asciidoc
Labels: backport 7.12, backport 7.x

#1575 Generate APIs using Elastic build artifacts API
  CONTRIBUTING.md
  elasticsearch/_async/client/__init__.py
  elasticsearch/_async/client/__init__.pyi
  elasticsearch/_async/client/cluster.py
  elasticsearch/_async/client/fleet.py
  elasticsearch/_async/client/fleet.pyi
  elasticsearch/_async/client/ml.py
  elasticsearch/_async/client/ml.pyi
  elasticsearch/_async/client/shutdown.py
  elasticsearch/_async/client/shutdown.pyi
  elasticsearch/_async/client/text_structure.py
  elasticsearch/client/__init__.py
  elasticsearch/client/__init__.pyi
  elasticsearch/client/cluster.py
  elasticsearch/client/fleet.py
  elasticsearch/client/fleet.pyi
  elasticsearch/client/ml.py
  elasticsearch/client/ml.pyi
  elasticsearch/client/shutdown.py
  elasticsearch/client/shutdown.pyi
  elasticsearch/client/text_structure.py
  utils/generate-api.py
Labels: backport 7.x

#1553 Add `ignore` kwarg to bulk/streaming_bulk to ignore error status codes
  elasticsearch/_async/helpers.py
  elasticsearch/_async/helpers.pyi
  elasticsearch/helpers/actions.py
  elasticsearch/helpers/actions.pyi
  test_elasticsearch/test_async/test_server/test_helpers.py
  test_elasticsearch/test_server/test_helpers.py
Labels: backport 7.x

#1583 [DOCS] Adds Release notes section to Py book
  docs/guide/index.asciidoc
  docs/guide/release-notes.asciidoc
Labels: 7.x, 8.x, docs

#1585 Add support for the HTTP API compatibility header
  docs/sphinx/connection.rst
  elasticsearch/connection/base.py
  elasticsearch/exceptions.py
  elasticsearch/helpers/errors.py
  elasticsearch/serializer.py
  test_elasticsearch/test_async/test_server/test_rest_api_spec.py
  test_elasticsearch/test_connection.py
  test_elasticsearch/test_serializer.py
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.13, backport 7.x
