Repository elastic/elasticsearch-py, pull requests merged in 2021-01, with the labels that each got.

#1496 Skip REST API test search/highlight/20_fvh[3]
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.10, backport 7.11, backport 7.9, backport 7.x

#1495 Use ElasticsearchWarning instead of ElasticsearchDeprecationWarning
  elasticsearch/__init__.py
  elasticsearch/connection/base.py
  elasticsearch/exceptions.py
  elasticsearch/exceptions.pyi
  test_elasticsearch/test_async/test_server/test_rest_api_spec.py
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.11, backport 7.x

#1504 Use gzip to compress the release tarball
  .ci/make.sh
Labels: backport 7.10, backport 7.11, backport 7.x

#1511 Implement run_contains for REST API Tests
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.11, backport 7.x

#1513 Add arbitrary_key to test_rest_api_spec
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.11, backport 7.x

#1520 [DOCS] Adds Configuration section to Python book
  docs/guide/configuration.asciidoc
  docs/guide/connection-pool.asciidoc
  docs/guide/connection-selector.asciidoc
  docs/guide/index.asciidoc
Labels: 7.x, backport 7.11, backport 7.x, docs

#1523 Update integration test suite with new Docker distribution format
  .ci/functions/cleanup.sh
  .ci/functions/imports.sh
  .ci/functions/wait-for-container.sh
  .ci/jobs/defaults.yml
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests
  .ci/test-matrix.yml
  CONTRIBUTING.md
  elasticsearch/helpers/test.py
  test_elasticsearch/README.rst
  test_elasticsearch/test_server/conftest.py
  test_elasticsearch/utils.py
Labels: backport 7.10, backport 7.11, backport 7.x
