Repository elastic/elasticsearch-py, pull requests merged in 2021-12, with the labels that each got.

#1820 Set a default User-Agent header
  elasticsearch/_sync/client/utils.py
  test_elasticsearch/test_transport.py
Labels: backport 8.0

#1823 Add 7.16.0 release notes
  docs/guide/release-notes.asciidoc
Labels: backport 7.16, backport 8.0

#1830 Add note about parameter ordering for upgrading from 6.x->7.0
  docs/guide/release-notes.asciidoc
Labels: backport 7.16, backport 8.0

#1833 Fix default 'User-Agent' header overriding HTTP headers
  elasticsearch/_async/client/_base.py
  elasticsearch/_sync/client/_base.py
  elasticsearch/_sync/client/utils.py
  test_elasticsearch/test_async/test_transport.py
  test_elasticsearch/test_client/test_options.py
  test_elasticsearch/test_transport.py
  test_elasticsearch/utils.py
Labels: backport 8.0

#1836 Add 7.16.1 release notes
  docs/guide/release-notes.asciidoc
Labels: backport 7.16, backport 8.0

#1843 Bumping version to 7.16.3
  elasticsearch/_version.py
Labels: 7.x

#1844 Bump to next 7.16 version
  elasticsearch/_version.py
Labels: 7.x

#1847 Add 7.16.2 release notes
  docs/guide/release-notes.asciidoc
Labels: backport 7.16, backport 8.0

#1848 Mark wheels as Python 3.x only
  setup.cfg
  test_elasticsearch/test_types/aliased_types.py
Labels: backport 8.0

#1853 Use 'body' instead of 'raw' for responses
  dev-requirements.txt
  elasticsearch/_async/client/_base.py
  elasticsearch/_async/helpers.py
  elasticsearch/_sync/client/_base.py
  elasticsearch/helpers/actions.py
  setup.py
  test_elasticsearch/test_async/test_server/test_helpers.py
  test_elasticsearch/test_async/test_server/test_mapbox_vector_tile.py
  test_elasticsearch/test_async/test_server/test_rest_api_spec.py
  test_elasticsearch/test_server/test_mapbox_vector_tile.py
  test_elasticsearch/test_server/test_responses.py
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 8.0
