Repository elastic/elasticsearch-py, pull requests merged in 2021-07, with the labels that each got.

#1631 Add release notes for 7.13.3
  docs/guide/release-notes.asciidoc
Labels: backport 7.13, backport 7.14, backport 7.x

#1635 Don't swallow unexpected errors during Elasticsearch verification step
  elasticsearch/_async/transport.py
  elasticsearch/transport.py
  test_elasticsearch/test_async/test_transport.py
  test_elasticsearch/test_transport.py
Labels: backport 7.14

#1640 Add transform_and_set to rest API Tests
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.14, backport 7.x

#1643 Bug fix typo #1642
  CONTRIBUTING.md
Labels: backport 7.13, backport 7.14, backport 7.x

#1589 Fix link to JSONSerializer in docs
  docs/sphinx/index.rst
Labels: backport 7.13, backport 7.14, backport 7.x

#1641 Added type hint for loop
  elasticsearch/_async/http_aiohttp.pyi
Labels: backport 7.x

#1649 Add release notes for 7.13.4
  docs/guide/release-notes.asciidoc
Labels: backport 7.13, backport 7.14, backport 7.x
