Repository elastic/elasticsearch-py, pull requests merged in 2021-09, with the labels that each got.

#1703 Reduce Pipeline time by running specific python version
  .ci/run-repository.sh
Labels: backport 7.x, backport 7.14, backport 7.15

#1702 Fix Pipelines
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.x, backport 7.14, backport 7.15

#1706 [DOCS] Adds a link to the Example Use section that points to an EC ingest example
  docs/guide/overview.asciidoc
Labels: 7.x, backport 7.x, docs, 8.x, backport 7.15

#1688 Add body field parameters to 'indices.create' API
  elasticsearch/_async/client/__init__.py
  elasticsearch/_async/client/__init__.pyi
  elasticsearch/_async/client/indices.py
  elasticsearch/_async/client/indices.pyi
  elasticsearch/_async/client/ml.py
  elasticsearch/_async/client/ml.pyi
  elasticsearch/client/__init__.py
  elasticsearch/client/__init__.pyi
  elasticsearch/client/indices.py
  elasticsearch/client/indices.pyi
  elasticsearch/client/ml.py
  elasticsearch/client/ml.pyi
  elasticsearch/client/utils.py
  elasticsearch/client/utils.pyi
  test_elasticsearch/test_client/test_document.py
  test_elasticsearch/test_client/test_indices.py
  test_elasticsearch/test_client/test_utils.py
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.15

#1713 Deprecate 'doc_type' for query parameters
  elasticsearch/_async/client/license.py
  elasticsearch/_async/client/license.pyi
  elasticsearch/_async/client/nodes.py
  elasticsearch/_async/client/nodes.pyi
  elasticsearch/client/license.py
  elasticsearch/client/license.pyi
  elasticsearch/client/nodes.py
  elasticsearch/client/nodes.pyi
  elasticsearch/client/utils.py
  test_elasticsearch/test_async/test_server/test_rest_api_spec.py
  test_elasticsearch/test_client/test_overrides.py
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.15

#1716 Delay importing numpy and pandas until necessary
  elasticsearch/serializer.py
Labels: backport 7.x, backport 7.15

#1720 Tweak language in compatibility section
  README.rst
  docs/guide/overview.asciidoc
  docs/sphinx/index.rst
Labels: backport 7.x, backport 7.14, backport 7.15

#1727 Add term-missing to pytest
  noxfile.py
  setup.cfg
Labels: backport 7.x, backport 7.15

#1729 Move coverage config to '.coveragerc'
  .coveragerc
  setup.cfg
Labels: backport 7.x, backport 7.15

#1736 Add 7.15.0 release notes to documentation
  docs/guide/release-notes.asciidoc
Labels: backport 7.x, backport 7.15

#1739 Bump Sphinx version
  dev-requirements.txt
Labels: backport 7.x, backport 7.15

#1735 Improve integration suite UX and make MVT test more general
  setup.cfg
  test_elasticsearch/test_async/test_server/test_mapbox_vector_tile.py
  test_elasticsearch/test_server/test_mapbox_vector_tile.py
  test_elasticsearch/test_server/test_rest_api_spec.py
Labels: backport 7.x, backport 7.15
