Repository elastic/elasticsearch-py, pull requests merged in 2021-06, with the labels that each got.

#1604 Skip default headers from AIOHttpConnection
  elasticsearch/_async/http_aiohttp.py
  test_elasticsearch/test_async/test_connection.py
  test_elasticsearch/test_connection.py
Labels: backport 7.13, backport 7.x

#1609 Handle RecursionError exception in perform_request
  elasticsearch/_async/http_aiohttp.py
  elasticsearch/connection/http_requests.py
  elasticsearch/connection/http_urllib3.py
Labels: backport 7.13, backport 7.x

#1610 Start testing on Python 3.10
  .ci/test-matrix.yml
  .github/workflows/ci.yml
  dev-requirements.txt
  elasticsearch/_async/http_aiohttp.py
  test_elasticsearch/test_async/test_connection.py
  test_elasticsearch/test_serializer.py
Labels: backport 7.13, backport 7.x

#1616 Add release notes to elastic.co/guide
  docs/guide/release-notes.asciidoc
Labels: backport 7.13, backport 7.x

#1620 AsyncTransport(sniff_on_start=True) should block further requests until complete
  elasticsearch/_async/transport.py
  elasticsearch/transport.py
  test_elasticsearch/test_async/test_transport.py
Labels: backport 7.x

#1624 Tolerate RecursionError not being defined in Python<3.5
  elasticsearch/_async/http_aiohttp.py
  elasticsearch/compat.py
  elasticsearch/compat.pyi
  elasticsearch/connection/http_requests.py
  elasticsearch/connection/http_urllib3.py
  test_elasticsearch/test_async/test_connection.py
  test_elasticsearch/test_connection.py
Labels: backport 7.13, backport 7.x

#1623 Verify connection to Elasticsearch
  elasticsearch/_async/transport.py
  elasticsearch/compat.py
  elasticsearch/exceptions.py
  elasticsearch/exceptions.pyi
  elasticsearch/transport.py
  test_elasticsearch/test_async/test_connection.py
  test_elasticsearch/test_async/test_transport.py
  test_elasticsearch/test_connection.py
  test_elasticsearch/test_transport.py
Labels: backport 7.14
