Repository elastic/elasticsearch-py, pull requests merged in 2023-11, with the labels that each got.

#2356 Update FastAPI example to use lifespan events
  docs/sphinx/async.rst
Labels: backport 7.17, backport 8.10, backport 8.11

#2346 Add release notes from 8.8.1 to 8.10.1
  docs/guide/release-notes.asciidoc
Labels: backport 8.11

#2367 Fix CI
  .github/workflows/ci.yml
  .readthedocs.yml
  dev-requirements.txt
  setup.cfg
  test_elasticsearch/test_async/test_server/test_helpers.py
Labels: backport 8.10, backport 8.11

#2374 [DOCS] Add interactive examples section to Sphinx docs
  docs/sphinx/index.rst
  docs/sphinx/interactive.rst
Labels: docs, backport 8.11

#2375 [DOCS] Separates sub-client sections to standalone pages
  docs/sphinx/api.rst
  docs/sphinx/api/autoscaling.rst
  docs/sphinx/api/cat.rst
  docs/sphinx/api/ccr.rst
  docs/sphinx/api/cluster.rst
  docs/sphinx/api/dangling-indices.rst
  docs/sphinx/api/elasticsearch.rst
  docs/sphinx/api/enrich-policies.rst
  docs/sphinx/api/eql.rst
  docs/sphinx/api/fleet.rst
  docs/sphinx/api/graph-explore.rst
  docs/sphinx/api/index-lifecycle-management.rst
  docs/sphinx/api/indices.rst
  docs/sphinx/api/ingest-pipelines.rst
  docs/sphinx/api/license.rst
  docs/sphinx/api/logstash.rst
  docs/sphinx/api/migration.rst
  docs/sphinx/api/ml.rst
  docs/sphinx/api/monitoring.rst
  docs/sphinx/api/nodes.rst
  docs/sphinx/api/query-rules.rst
  docs/sphinx/api/rollup-indices.rst
  docs/sphinx/api/search-application.rst
  docs/sphinx/api/searchable-snapshots.rst
  docs/sphinx/api/security.rst
  docs/sphinx/api/shutdown.rst
  docs/sphinx/api/snapshot-lifecycle-management.rst
  docs/sphinx/api/snapshots.rst
  docs/sphinx/api/snapshottable-features.rst
  docs/sphinx/api/sql.rst
  docs/sphinx/api/synonyms.rst
  docs/sphinx/api/tasks.rst
  docs/sphinx/api/text-structure.rst
  docs/sphinx/api/tls-ssl.rst
  docs/sphinx/api/transforms.rst
  docs/sphinx/api/watcher.rst
  docs/sphinx/api/x-pack.rst
  docs/sphinx/async.rst
  docs/sphinx/exceptions.rst
Labels: docs, backport 8.11
