Repository elastic/elasticsearch-py, pull requests merged in 2024-05, with the labels that each got.

#2545 Fix code generation
  .buildkite/Dockerfile
  noxfile.py
Labels: backport 8.13, backport 8.14

#2535 setup and update code examples
  docs/examples/0eccea755bd4f6dd47579a9022690546.asciidoc
  docs/examples/1605be45a5711d1929d6ad2d1ae0f797.asciidoc
  docs/examples/197dc41c8df9629e145b3064c63b2ccc.asciidoc
  docs/examples/1cd3b9d65576a9212eef898eb3105758.asciidoc
  docs/examples/2d9b30acd6b5683f39d53494c0dd779c.asciidoc
  docs/examples/36da9668fef56910370f16bfb772cc40.asciidoc
  docs/examples/3c5d5a5c34a62724942329658c688f5e.asciidoc
  docs/examples/3f3b3e207f79303ce6f86e03e928e062.asciidoc
  docs/examples/4207219a892339e8f3abe0df8723dd27.asciidoc
  docs/examples/4498b9d3b0c77e1b9ef6664ff5963ce2.asciidoc
  docs/examples/45ef5156dbd2d3fd4fd22b8d99f7aad4.asciidoc
  docs/examples/4e1f02928ef243bf07fd425754b7642b.asciidoc
  docs/examples/58f72be60c25752d7899a35fc60fe6eb.asciidoc
  docs/examples/5e099493f135ff7bd614e935c4f2bf5a.asciidoc
  docs/examples/640a89d0b39630269433425ff476faf3.asciidoc
  docs/examples/64ffaa6814ec1ec4f59b8f33b47cffb4.asciidoc
  docs/examples/75e229852d1404040bb2e83723c0f1db.asciidoc
  docs/examples/7cd23457e220c8b64c5b0041d2acc27a.asciidoc
  docs/examples/7e49705769c42895fb7b1e2ca028ff47.asciidoc
  docs/examples/90112d594b934c0111b7303b9f91cb7f.asciidoc
  docs/examples/90631797c7fbda43902abf2cc0ea8304.asciidoc
  docs/examples/92f073762634a4b2274f71002494192e.asciidoc
  docs/examples/a21a7bf052b41f5b996dc58f7b69770f.asciidoc
  docs/examples/b14122481ae1f158f1a9a1bfbc4a41b1.asciidoc
  docs/examples/b6a6aa9ba20e9a019371ae268488833f.asciidoc
  docs/examples/c0a4b0c1c6eff14da8b152ceb19c1c31.asciidoc
  docs/examples/c5bc577ff92f889225b0d2617adcb48c.asciidoc
  docs/examples/cb2f70601cb004b9ece9b0b43a9dc21a.asciidoc
  docs/examples/cc0cca5556ec6224c7134c233734beed.asciidoc
  docs/examples/e26c96978096ccc592849cca9db67ffc.asciidoc
  docs/examples/ead4d875877d618594d0cdbdd9b7998b.asciidoc
  docs/examples/ed250b74bc77c15bb794f55a12d762c3.asciidoc
  docs/examples/f27c28ddbf4c266b5f42d14da837b8de.asciidoc
  docs/examples/f3c696cd63a3f042e62cbb94b75c2427.asciidoc
  docs/examples/fde3463ddf136fdfff1306a60986515e.asciidoc
  utils/generate-examples.py
Labels: Category: Enhancement, Area: Documentation, backport 8.14

#2551 Remove redundant/deprecated `np.float_` use to fix NumPy 2.0 compat
  elasticsearch/serializer.py
  test_elasticsearch/test_serializer.py
Labels: backport 8.14

#2553 Revert "Add Connector API (#2531)"
  docs/sphinx/api.rst
  docs/sphinx/api/connector.rst
  elasticsearch/_async/client/__init__.py
  elasticsearch/_async/client/connector.py
  elasticsearch/_sync/client/__init__.py
  elasticsearch/_sync/client/connector.py
  elasticsearch/client.py
Labels: backport 8.14

#2554 adding index module code examples
  docs/examples/156bc64c94f9f3334fbce25165d2286a.asciidoc
  docs/examples/17e6f3fac556f08a78f7a876e71acb89.asciidoc
  docs/examples/2342a56279106ea643026df657bf7f88.asciidoc
  docs/examples/23af230e824f48b9cd56a4cf973d788c.asciidoc
  docs/examples/25d40d3049e57e2bb70c2c5b88bd7b87.asciidoc
  docs/examples/28ac880057135e46b3b00c7f3976538c.asciidoc
  docs/examples/2f07b81fd47ec3b074242a760f0c4e9e.asciidoc
  docs/examples/34cdeefb09bbbe5206957a8bc1bd513d.asciidoc
  docs/examples/48de51de87a8ad9fd8b8db1ca25b85c1.asciidoc
  docs/examples/528e5f1c345c3769248cc6889e8cf552.asciidoc
  docs/examples/553d79817bb1333970e99507c37a159a.asciidoc
  docs/examples/5f8fb5513d4f725434db2f517ad4298f.asciidoc
  docs/examples/7b3e913368e96eaa6e22e0d03c81310e.asciidoc
  docs/examples/844928da2ff9a1394af5347a5e2e4f78.asciidoc
  docs/examples/8703f3b1b3895543abc36e2a7a0013d3.asciidoc
  docs/examples/8d7193902a353872740a3324c60c5001.asciidoc
  docs/examples/9de4ea9d5f3d427a71ee07d998cb5611.asciidoc
  docs/examples/a38f29375eabd0103f8d7c00b17bb0ab.asciidoc
  docs/examples/a425fcab60f603504becee7d001f0a4b.asciidoc
  docs/examples/beba2a9795c8a13653e1edf64eec4357.asciidoc
  docs/examples/d4fb482a51d67a1af48e429af6019a46.asciidoc
  docs/examples/dad2d4add751fde5c39475ca709cc14b.asciidoc
  docs/examples/dfa16b7300d225e013f23625f44c087b.asciidoc
  docs/examples/e1f6ea7c0937cf7e6ea7e8209e52e8bb.asciidoc
  docs/examples/e3b3a8ae12ab947ad3ba96eb228402ca.asciidoc
  docs/examples/fc8a426f8a5112e61e2acb913982a8d9.asciidoc
  utils/generate-examples.py
Labels: Category: Enhancement, Area: Documentation, backport 8.14

#2564 Mark requests 2.32.2 as incompatible
  setup.py
Labels: backport 8.13, backport 8.14

#2570 Fix missing dependency in utils/build-dists.py
  utils/build-dists.py
Labels: backport 8.13, backport 8.14
