Repository elastic/elasticsearch-py, pull requests merged in 2024-02, with the labels that each got.

#2415 Use unquote() directly instead of wrapper
  elasticsearch/_sync/client/utils.py
Labels: backport 8.12

#2417 Add mappings and bulk to quickstart page
  docs/sphinx/quickstart.rst
Labels: backport 8.12

#2437 Restore .ci/make.sh file
  .github/make.sh
Labels: backport 8.12

#2427 Fix but deprecate parameter aliases in body parameter
  elasticsearch/_sync/client/utils.py
  test_elasticsearch/test_client/test_rewrite_parameters.py
Labels: backport 8.12, backport 8.13

#2449 Fix example generation
  docs/examples/08f20902821a4f7a73ce7b959c5bdbdc.asciidoc
  docs/examples/13d90ba227131aefbf4fcfd5992e662a.asciidoc
  docs/examples/178c920d5e8ec0071f77290fa059802c.asciidoc
  docs/examples/1aa91d3d48140d6367b6cabca8737b8f.asciidoc
  docs/examples/20005d8a6555b259b299d862cd218701.asciidoc
  docs/examples/2fea3e324939cc7e9c396964aeee7111.asciidoc
  docs/examples/39ce44333d28ed2b833722d3e3cb06f3.asciidoc
  docs/examples/3e8ed6ae016eb823cb00d9035b8ac459.asciidoc
  docs/examples/64b9baa6d7556b960b29698f3383aa31.asciidoc
  docs/examples/6b0288acb739c4667d41339e5100c327.asciidoc
  docs/examples/7cd3d8388c51a9f6ee3f730cdaddbb89.asciidoc
  docs/examples/7f56755fb6c42f7e6203339a6d0cb6e6.asciidoc
  docs/examples/7f697eb436dfa3c30dfe610d8c32d132.asciidoc
  docs/examples/8cd00a3aba7c3c158277bc032aac2830.asciidoc
  docs/examples/ac497917ef707538198a8458ae3d5c6b.asciidoc
  docs/examples/ae9ccfaa146731ab9176df90670db1c2.asciidoc
  docs/examples/b52951b78cd5fb2f9353d1c7e6d37070.asciidoc
  docs/examples/bfdad8a928ea30d7cf60d0a0a6bc6e2e.asciidoc
  docs/examples/c0ebaa33e750b87555dc352073f692e8.asciidoc
  docs/examples/c9c396b94bb88098477e2b08b55a12ee.asciidoc
  docs/examples/dbc50b8c934171e94604575a8b36f349.asciidoc
  docs/examples/eec051555c8050d017d3fe38ea59e3a0.asciidoc
  docs/examples/f4f557716049b23f8840d58d71e748f0.asciidoc
  utils/generate-examples.py
Labels: backport 8.12, backport 8.13

#2455 Bring 8.12.1 release notes to main
  docs/guide/release-notes.asciidoc
  elasticsearch/_version.py
Labels: backport 8.13

#2458 [DOCS] Adds compatibility matrix to docs and readme
  README.rst
  docs/guide/installation.asciidoc
  docs/guide/overview.asciidoc
  docs/sphinx/index.rst
Labels: docs, backport 8.12, backport 8.13

#2461 Add cluster doc code examples
  docs/examples/1cecd4d87a92427175157d41859df2af.asciidoc
  docs/examples/2cd8439db5054c93c49f1bf50433e1bb.asciidoc
  docs/examples/2fc80a2ad1ca8b2dcb13ed1895b8e861.asciidoc
  docs/examples/3541d4a85e27b2c3896a7a7ee98b4b37.asciidoc
  docs/examples/4029af36cb3f8202549017f7378803b4.asciidoc
  docs/examples/4ca15672fc5ab1d80a127d086b6d2837.asciidoc
  docs/examples/87733deeea4b441b595d19a0f97346f0.asciidoc
  docs/examples/9d79645ab3a9da3f63c54a1516214a5a.asciidoc
  docs/examples/ab8de34fcfc0277901cb39618ecfc9d5.asciidoc
  docs/examples/ac85e05c0bf2fd5099fbcb9c492f447e.asciidoc
  docs/examples/e5901f48eb8a419b878fc2cb815d8691.asciidoc
  docs/examples/eff8ecaed1ed084909c64450fc363a20.asciidoc
  utils/generate-examples.py
Labels: enhancement, docs, backport 8.13
