Repository elastic/elasticsearch-py, pull requests merged in 2025-02, with the labels that each got.

#2779 Switch to Black 2025 and isort 6
  elasticsearch/dsl/search_base.py
  noxfile.py
  test_elasticsearch/test_dsl/test_result.py
Labels: Area: CI, Category: Not an issue, backport 8.x, backport 8.17, backport 8.18

#2790 Simplify lint and format nox sessions
  noxfile.py
Labels: backport 8.x, backport 8.17, backport 8.18

#2794 Reduce the number of black and isort calls
  utils/run-unasync-dsl.py
Labels: backport 8.x, backport 8.18

#2780 autogenerate field classes from schema
  elasticsearch/dsl/field.py
  elasticsearch/dsl/types.py
  utils/dsl-generator.py
  utils/templates/field.py.tpl
Labels: backport 8.x, backport 8.18

#2798 Explain how to use sub clients in API docs
  docs/sphinx/api/elasticsearch.rst
  docs/sphinx/conf.py
  elasticsearch/client.py
Labels: backport 8.x, backport 8.17, backport 8.18

#2805 [docs] Add the new docs CI checks
  .github/workflows/comment-on-asciidoc-changes.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: Area: Documentation
