Repository elastic/elasticsearch-py, pull requests merged in 2025-03, with the labels that each got.

#2826 [docs] Fix external links
  docs/reference/client-helpers.md
  docs/reference/connecting.md
  docs/reference/opentelemetry.md
Labels: Area: Documentation

#2828 [DOCS] Delete preview action for old Asciidoc system
  .github/workflows/docs-preview.yml
Labels: Area: Documentation, backport 9.0

#2825 Fix logo URL
  README.md
  docs/images/logo-elastic-glyph-color.svg
Labels: backport 8.x, backport 8.17, backport 8.18, backport 9.0

#2854 Updates navigation titles and descriptions for release notes
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: Area: Documentation

#2853 [docs] Miscellaneous docs clean up
  docs/docset.yml
  docs/reference/getting-started.md
  docs/reference/images/create-api-key.png
  docs/reference/images/es-endpoint.jpg
  docs/reference/images/otel-waterfall-retry.png
  docs/reference/images/otel-waterfall-with-http.png
  docs/reference/images/otel-waterfall-without-http.png
  docs/reference/opentelemetry.md
Labels: Area: Documentation

#2859 [docs] Add missing mapped pages
  docs/release-notes/index.md
Labels: Area: Documentation

#2857 Use class-based queries and type-hinted documents in DSL documentation examples
  docs/reference/dsl_how_to_guides.md
  docs/reference/dsl_migrating.md
  docs/reference/dsl_tutorials.md
  docs/reference/elasticsearch-dsl.md
  docs/reference/toc.yml
  elasticsearch/dsl/search_base.py
Labels: backport 9.0

#2860 Handle new aggregation range types Pythonically
  elasticsearch/dsl/aggs.py
  elasticsearch/dsl/faceted_search_base.py
  elasticsearch/dsl/field.py
  elasticsearch/dsl/query.py
  elasticsearch/dsl/types.py
  elasticsearch/dsl/wrappers.py
  utils/dsl-generator.py
  utils/templates/aggs.py.tpl
Labels: backport 9.0

#2861 [docs] Add param notes to DSL search.delete documentation, fix broken links
  docs/reference/dsl_how_to_guides.md
  elasticsearch/dsl/_async/search.py
  elasticsearch/dsl/_sync/search.py
  elasticsearch/dsl/faceted_search_base.py
Labels: backport 9.0
