Repository elastic/elasticsearch-py, pull requests merged in 2025-05, with the labels that each got.

#2952 Intro paragraph for the readthedocs API reference
  docs/reference/index.md
  docs/sphinx/index.rst
Labels: backport 9.0

#2958 [Docs] Fix broken link to RTD helpers page
  docs/reference/client-helpers.md
  docs/reference/index.md
Labels: Area: Documentation, backport 9.0

#2969 Stop using event_loop fixture
  docs/reference/async.md
  test_elasticsearch/test_async/test_transport.py
Labels: backport 8.19, backport 8.18, backport 9.0

#2974 Fix some new type warnings from mypy
  elasticsearch/dsl/_async/document.py
  elasticsearch/dsl/_sync/document.py
  elasticsearch/dsl/field.py
  elasticsearch/dsl/query.py
  elasticsearch/dsl/types.py
Labels: backport 8.19, backport 9.0
