Repository elastic/elasticsearch-py, pull requests merged in 2025-04, with the labels that each got.

#2872 Revert "Remove deprecated http_auth parameter (#2839)"
  elasticsearch/_async/client/__init__.py
  elasticsearch/_async/client/_base.py
  elasticsearch/_async/client/utils.py
  elasticsearch/_async/helpers.py
  elasticsearch/_sync/client/__init__.py
  elasticsearch/_sync/client/_base.py
  elasticsearch/_sync/client/utils.py
  elasticsearch/helpers/actions.py
  test_elasticsearch/test_async/test_server/test_helpers.py
  test_elasticsearch/test_client/test_deprecated_options.py
  test_elasticsearch/test_client/test_requests_auth.py
  test_elasticsearch/test_client/test_rewrite_parameters.py
  test_elasticsearch/test_server/test_helpers.py
Labels: backport 9.0

#2843 Add querying docs
  docs/images/python-example.png
  docs/reference/querying.md
  docs/reference/toc.yml
Labels: backport 9.0

#2873 Add back inference.inference API
  elasticsearch/_async/client/inference.py
  elasticsearch/_sync/client/inference.py
  elasticsearch/_sync/client/utils.py
Labels: backport 8.x, backport 8.18, backport 9.0

#2900 [docs] Update APM, Synthetics, Uptime links
  docs/reference/opentelemetry.md
Labels: Area: Documentation

#2899 Revert "Add back inference.inference API (#2873)"
  elasticsearch/_async/client/inference.py
  elasticsearch/_sync/client/inference.py
  elasticsearch/_sync/client/utils.py
Labels: backport 8.x, backport 8.18, backport 9.0

#2904 [DOCS]:Update links to ESQL reference docs
  docs/reference/esql-pandas.md
Labels: Area: Documentation, backport 9.0

#2871 Only wipe user content between tests
  test_elasticsearch/utils.py
Labels: backport 8.x, backport 8.18, backport 9.0

#2911 Fix release notes URL
  CHANGELOG.md
Labels: backport 8.x, backport 8.18, backport 9.0

#2912 [8.x] Remove table of contents in release notes
  docs/guide/release-notes.asciidoc
Labels: backport 8.18

#2776 Reorganization of the Sphinx docs to only include reference pages
  docs/sphinx/api_helpers.rst
  docs/sphinx/async.rst
  docs/sphinx/async_api_helpers.rst
  docs/sphinx/async_dsl.rst
  docs/sphinx/async_es_api.rst
  docs/sphinx/dsl.rst
  docs/sphinx/es_api.rst
  docs/sphinx/helpers.rst
  docs/sphinx/index.rst
  docs/sphinx/interactive.rst
  docs/sphinx/quickstart.rst
Labels: backport 8.x, backport 8.18, backport 9.0

#2929 [docs] Fix image paths for docs-assembler
  docs/reference/getting-started.md
  docs/reference/opentelemetry.md
Labels: Area: Documentation, backport 9.0

#2928 Clarify Elasticsearch 9.x compatibility
  README.md
  docs/reference/index.md
Labels: backport 9.0

#2932 Surface caused_by in ApiError
  elasticsearch/exceptions.py
  test_elasticsearch/test_exceptions.py
Labels: backport 8.x, backport 9.0

#2940 [docs] Fix various syntax and rendering errors
  docs/reference/client-helpers.md
  docs/reference/images/python-example.png
  docs/reference/querying.md
Labels: Area: Documentation, backport 9.0

#2936 Add breaking changes to release notes
  docs/release-notes/breaking-changes.md
  docs/release-notes/index.md
Labels: backport 9.0
