Repository elastic/elasticsearch-py, pull requests merged in 2025-08, with the labels that each got.

#3018 Address integration test failures in Python 3.8
  test_elasticsearch/test_server/test_rest_api_spec.py
  test_elasticsearch/utils.py
Labels: backport 8.19, backport 8.17, backport 8.18, backport 9.0, backport 9.1

#3017 ES|QL query builder robustness fixes
  docs/reference/esql-query-builder.md
  elasticsearch/esql/__init__.py
  elasticsearch/esql/esql.py
  elasticsearch/esql/functions.py
  test_elasticsearch/test_dsl/test_integration/_async/test_esql.py
  test_elasticsearch/test_dsl/test_integration/_sync/test_esql.py
  test_elasticsearch/test_esql.py
Labels: backport 8.19, backport 9.0, backport 9.1

#3038 Fix new parameter name in breaking changes docs
  docs/release-notes/breaking-changes.md
Labels: backport 9.0, backport 9.1

#3041 DSL: preserve the `skip_empty` setting in `to_dict()` recursive serializations
  elasticsearch/dsl/field.py
  elasticsearch/dsl/utils.py
  test_elasticsearch/test_dsl/test_integration/_async/test_document.py
  test_elasticsearch/test_dsl/test_integration/_sync/test_document.py
  utils/templates/field.py.tpl
Labels: backport 8.19, backport 8.18, backport 9.0, backport 9.1
